/**
 * This file is auto-generated by the build script.
 * It consolidates API functions for use in the application.
 * Do not edit manually.
 */
import _applicationMap from './src/applicationMap.js';
import _awesomenessNormalizeRequest from './src/awesomenessNormalizeRequest.js';
import _brotliJsonResponse from './src/brotliJsonResponse.js';
import _checkAccess from './src/checkAccess.js';
import _componentAndPageMemory from './src/componentAndPageMemory.js';
import _componentDependencies from './src/componentDependencies.js';
import _config from './src/config.js';
import _extractUiComponentRefs from './src/extractUiComponentRefs.js';
import _fetchPage from './src/fetchPage.js';
import _getConfig from './src/getConfig.js';
import _getMD from './src/getMD.js';
import _init from './src/init.js';
import _koa_attachAwesomenessRequest from './src/koa/attachAwesomenessRequest.js';
import _koa_cors from './src/koa/cors.js';
import _koa_errorHandler from './src/koa/errorHandler.js';
import _koa_finalFormat from './src/koa/finalFormat.js';
import _koa_jsonBodyParser from './src/koa/jsonBodyParser.js';
import _koa_routeRequest from './src/koa/routeRequest.js';
import _koa_serverUp from './src/koa/serverUp.js';
import _koa_staticFiles from './src/koa/staticFiles.js';
import _koa_timeout from './src/koa/timeout.js';
import _pageInfo from './src/pageInfo.js';
import _reRoute from './src/reRoute.js';
import _resolveRealCasePath from './src/resolveRealCasePath.js';
import _specialPaths from './src/specialPaths.js';
import _start from './src/start.js';
import _validateRequest from './src/validateRequest.js';
import _ws_handlers from './src/ws/handlers.js';
import _ws_index from './src/ws/index.js';

export { _applicationMap as applicationMap };
export { _awesomenessNormalizeRequest as awesomenessNormalizeRequest };
export { _brotliJsonResponse as brotliJsonResponse };
export { _checkAccess as checkAccess };
export { _componentAndPageMemory as componentAndPageMemory };
export { _componentDependencies as componentDependencies };
export { _config as config };
export { _extractUiComponentRefs as extractUiComponentRefs };
export { _fetchPage as fetchPage };
export { _getConfig as getConfig };
export { _getMD as getMD };
export { _init as init };
export { _pageInfo as pageInfo };
export { _reRoute as reRoute };
export { _resolveRealCasePath as resolveRealCasePath };
export { _specialPaths as specialPaths };
export { _start as start };
export { _validateRequest as validateRequest };

export const koa = {
	attachAwesomenessRequest: _koa_attachAwesomenessRequest,
	cors: _koa_cors,
	errorHandler: _koa_errorHandler,
	finalFormat: _koa_finalFormat,
	jsonBodyParser: _koa_jsonBodyParser,
	routeRequest: _koa_routeRequest,
	serverUp: _koa_serverUp,
	staticFiles: _koa_staticFiles,
	timeout: _koa_timeout
};

export const ws = {
	handlers: _ws_handlers,
	index: _ws_index
};


export default {
	applicationMap: _applicationMap,
	awesomenessNormalizeRequest: _awesomenessNormalizeRequest,
	brotliJsonResponse: _brotliJsonResponse,
	checkAccess: _checkAccess,
	componentAndPageMemory: _componentAndPageMemory,
	componentDependencies: _componentDependencies,
	config: _config,
	extractUiComponentRefs: _extractUiComponentRefs,
	fetchPage: _fetchPage,
	getConfig: _getConfig,
	getMD: _getMD,
	init: _init,
	pageInfo: _pageInfo,
	reRoute: _reRoute,
	resolveRealCasePath: _resolveRealCasePath,
	specialPaths: _specialPaths,
	start: _start,
	validateRequest: _validateRequest,
	koa: {
		attachAwesomenessRequest: _koa_attachAwesomenessRequest,
		cors: _koa_cors,
		errorHandler: _koa_errorHandler,
		finalFormat: _koa_finalFormat,
		jsonBodyParser: _koa_jsonBodyParser,
		routeRequest: _koa_routeRequest,
		serverUp: _koa_serverUp,
		staticFiles: _koa_staticFiles,
		timeout: _koa_timeout,
	},
	ws: {
		handlers: _ws_handlers,
		index: _ws_index,
	},
};