/**
 * This file is auto-generated by the build script.
 * It consolidates API type declarations for use in the application.
 * Do not edit manually.
 */
import type _applicationMap from './applicationMap';
import type _awesomenessNormalizeRequest from './awesomenessNormalizeRequest';
import type _brotliJsonResponse from './brotliJsonResponse';
import type _checkAccess from './checkAccess';
import type _componentAndPageMemory from './componentAndPageMemory';
import type _componentDependencies from './componentDependencies';
import type _config from './config';
import type _extractUiComponentRefs from './extractUiComponentRefs';
import type _fetchPage from './fetchPage';
import type _getConfig from './getConfig';
import type _getMD from './getMD';
import type _init from './init';
import type _koa_attachAwesomenessRequest from './koa/attachAwesomenessRequest';
import type _koa_cors from './koa/cors';
import type _koa_errorHandler from './koa/errorHandler';
import type _koa_finalFormat from './koa/finalFormat';
import type _koa_jsonBodyParser from './koa/jsonBodyParser';
import type _koa_routeRequest from './koa/routeRequest';
import type _koa_serverUp from './koa/serverUp';
import type _koa_staticFiles from './koa/staticFiles';
import type _koa_timeout from './koa/timeout';
import type _pageInfo from './pageInfo';
import type _reRoute from './reRoute';
import type _resolveRealCasePath from './resolveRealCasePath';
import type _specialPaths from './specialPaths';
import type _start from './start';
import type _validateRequest from './validateRequest';
import type _ws_handlers from './ws/handlers';
import type _ws_index from './ws/index';

export declare const applicationMap: typeof _applicationMap;
export declare const awesomenessNormalizeRequest: typeof _awesomenessNormalizeRequest;
export declare const brotliJsonResponse: typeof _brotliJsonResponse;
export declare const checkAccess: typeof _checkAccess;
export declare const componentAndPageMemory: typeof _componentAndPageMemory;
export declare const componentDependencies: typeof _componentDependencies;
export declare const config: typeof _config;
export declare const extractUiComponentRefs: typeof _extractUiComponentRefs;
export declare const fetchPage: typeof _fetchPage;
export declare const getConfig: typeof _getConfig;
export declare const getMD: typeof _getMD;
export declare const init: typeof _init;
export declare const pageInfo: typeof _pageInfo;
export declare const reRoute: typeof _reRoute;
export declare const resolveRealCasePath: typeof _resolveRealCasePath;
export declare const specialPaths: typeof _specialPaths;
export declare const start: typeof _start;
export declare const validateRequest: typeof _validateRequest;

export declare const koa: {
	attachAwesomenessRequest: typeof _koa_attachAwesomenessRequest;
	cors: typeof _koa_cors;
	errorHandler: typeof _koa_errorHandler;
	finalFormat: typeof _koa_finalFormat;
	jsonBodyParser: typeof _koa_jsonBodyParser;
	routeRequest: typeof _koa_routeRequest;
	serverUp: typeof _koa_serverUp;
	staticFiles: typeof _koa_staticFiles;
	timeout: typeof _koa_timeout;
};

export declare const ws: {
	handlers: typeof _ws_handlers;
	index: typeof _ws_index;
};


declare const _default: {
	applicationMap: typeof _applicationMap;
	awesomenessNormalizeRequest: typeof _awesomenessNormalizeRequest;
	brotliJsonResponse: typeof _brotliJsonResponse;
	checkAccess: typeof _checkAccess;
	componentAndPageMemory: typeof _componentAndPageMemory;
	componentDependencies: typeof _componentDependencies;
	config: typeof _config;
	extractUiComponentRefs: typeof _extractUiComponentRefs;
	fetchPage: typeof _fetchPage;
	getConfig: typeof _getConfig;
	getMD: typeof _getMD;
	init: typeof _init;
	pageInfo: typeof _pageInfo;
	reRoute: typeof _reRoute;
	resolveRealCasePath: typeof _resolveRealCasePath;
	specialPaths: typeof _specialPaths;
	start: typeof _start;
	validateRequest: typeof _validateRequest;
	koa: {
		attachAwesomenessRequest: typeof _koa_attachAwesomenessRequest,
		cors: typeof _koa_cors,
		errorHandler: typeof _koa_errorHandler,
		finalFormat: typeof _koa_finalFormat,
		jsonBodyParser: typeof _koa_jsonBodyParser,
		routeRequest: typeof _koa_routeRequest,
		serverUp: typeof _koa_serverUp,
		staticFiles: typeof _koa_staticFiles,
		timeout: typeof _koa_timeout,
	},
	ws: {
		handlers: typeof _ws_handlers,
		index: typeof _ws_index,
	},
};

export default _default;
