import { writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import { build, getAllFiles, combineFiles } from '@awesomeness-js/utils';
import { dynamicCSS } from './core/css/dynamic.js';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import cssnano from 'cssnano';
import postcss from 'postcss';

async function minifyCSS(cssString) {

	try {

		// Process the CSS using PostCSS and cssnano plugin
		const result = await postcss([ cssnano ]).process(cssString, { from: undefined });

		return result.css; // The minified CSS

	} catch (error) {

		console.error('Error minifying CSS:', error);
		
		return null;

	}

}


async function buildUI(){
	
	const __filename = fileURLToPath(import.meta.url);
	const __dirname = dirname(__filename);
	const coreDir = join(__dirname, 'core');
	

	await build({
		src: './awesomeness-ui/components',
		dest: './ui-intellisense.js',
		dts: false,
		fileTypes: [ 'js' ],
		ignore: [
			'*.iif.js',
			'*.jquery.js',
			'*.jQuery.js',
			'*.test.js',
			'*.css',
			'*.css.js'
		]
	});


	const cssBuilds = getAllFiles('.', {
		dir: './awesomeness-ui/components',
		fileTypes: [
			'css.js'
		]
	});


	if(cssBuilds.length > 0){

		await Promise.all(cssBuilds.map(async (file) => {

			try {

				const { cssBuild } = await import(`../${file}`);

				await cssBuild();

			} catch (e) {

				console.error(`Error importing CSS build file: ${file}`, e);
				
				return;
			
			}

		
		}));

	}


	// must be done in order
	let js = `
/**
 * This file is auto-generated by Awesomeness UI build script.
 * It consolidates UI functions for use in the application.
 * Do not edit manually.
 */
window.ui = {};

`;

	js += readFileSync(join(coreDir, 'js', 'jquery-3.7.1.min.js'), 'utf8');
	js += "\n " + readFileSync(join(coreDir, 'js', 'app.js'), 'utf8');
	js += "\n " + combineFiles(join(coreDir, 'js', 'app'), 'js');

	writeFileSync(join(coreDir, 'public', 'app.js'), js);

	let css = "";

	css += combineFiles(join(coreDir, 'css'), 'css');

	css += "\n";

	// dynamic css
	css += dynamicCSS();

	const cssMini = await minifyCSS(css);

	writeFileSync(join(coreDir, 'public', 'app.css'), cssMini);

	return true;

}

export default buildUI;